#!/bin/bash

url="$1"
cut=$(echo "$url" | grep -oP "[^/]/[^/]" | wc -l)
echo "cut: $cut"

if [ ! -d "$2" ] ; then
  mkdir -p "$2"
fi
cd "$2" || exit 1

wget \
  --mirror \
  --no-parent \
  --no-host-directories \
  --cut-dirs "$cut" \
  --reject mirrorlist,html,robots.txt \
  --reject-regex '(.*)\?(.*)' \
  "$url"
