#!/bin/bash

SNAPSHOT_DIR=".snapshot"
SNAPSHOT_AGE_MAX=100
TODAY=$(date +%Y%m%d)
MONTH=$(date +%Y%m)

if [ $# -gt 0 ] ; then
  cat "$SNAPSHOT_DIR/cache"
  exit
fi

# TODO Probably end up just snapshoting /iso directory and can read changes from
# that location. Having older ISOs since those break would be nice as well.
# Could also limit this to last month since they should never change.
./downloadz "http://download.opensuse.org/tumbleweed/iso/?P=Changes.$MONTH*.txt" "$SNAPSHOT_DIR"

echo -n > "$SNAPSHOT_DIR/cache"
for snapshot in $(find "$SNAPSHOT_DIR" -name "Changes.*.txt" | grep -oP "\d+" | sort -r) ; do
  if [ $(( $TODAY - $snapshot )) -gt $SNAPSHOT_AGE_MAX ] ; then
    break
  fi
  echo $snapshot | tee -a "$SNAPSHOT_DIR/cache"
done

# TODO Remove old changes, or end up reading directly and do not care.
